---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
drinks_content <- read_csv("data/starbucks_drinkMenu_expanded.csv")
```

```{r}
head(drinks_content,5)
```

```{r}
tail(drinks_content,5)
```

```{r}
drinks_content
```

```{r}
dim(drinks_content)

```

```{r}
names(drinks_content)
```

```{r}
summary(drinks_content$Calories)
hist(drinks_content$Calories)
```

```{r}
boxplot(drinks_content$Calories)
```

```{r}
outliers <- boxplot(drinks_content$Calories, plot=FALSE)$out
print(outliers)
```

#q4
```{r}
drinks <- select(drinks_content, Beverage_category, Beverage, Beverage_prep, Calories)

is.na(drinks$Calories)
```

```{r}
espresso_drinks <- filter(drinks, Beverage_category == "Classic Espresso Drinks")
espresso_drinks
```

```{r}
drink_calories <- mutate(espresso_drinks, calorie_diff = 135 - Calories)
drink_calories
```

```{r}
drinks_grouped <- group_by(drink_calories, Beverage_prep)

drinks_summary <- summarise(drinks_grouped, mean_cal = mean(Calories))

arrange(drinks_summary,desc(mean_cal))
```

```{r}
drinks_pipe <- drinks_content %>%
    select(Beverage_category, Beverage, Beverage_prep, Calories) %>%
    filter(Beverage_category == "Classic Espresso Drinks") %>%
    mutate(calorie_diff = 135 - Calories) %>%
    group_by(Beverage_prep) %>%
    summarise(mean_cal = mean(Calories)) %>%
    arrange(desc(mean_cal))
drinks_pipe
```

```{r}
least_calories <- drink_calories %>%
  arrange(Calories) %>%
  mutate(ranking = min_rank(Calories)) %>%
  filter(ranking <=2)

least_calories
```

```{r}
most_calories <- drink_calories %>%
  mutate(ranking = min_rank(desc(Calories))) %>%
  filter(ranking <=2)

most_calories
```

```{r}
above_average_calories <- drink_calories %>%
  group_by(Beverage_prep) %>%
  mutate(group_mean_cals = mean(Calories)) %>% #this line isn't necessary but can be helpful in understanding what the filter line is 
  filter(Calories > mean(Calories))

above_average_calories
```

```{r}
drinks_distribution <- drinks_grouped %>%
  filter(cume_dist(desc(Calories)) < 0.25) %>%
  select(Beverage_category,Beverage_prep)

drinks_distribution
```

```{r}
names(drinks_distribution)

```

