---
title: "R Notebook"
output: html_notebook
---


```{r}
library(RPostgreSQL)
library(keyring)
```

```{r}
# first, let's get our credentials from the local keyring
keyring_unlock(keyring = "local")
username <- key_get(service = "postgresql_username", keyring = "local")
password <- key_get(service = "postgresql_password", keyring = "local")
keyring_lock(keyring = "local")

# next, we create a connection to the database
my_db_connection <- dbConnect(drv = PostgreSQL(max.con = 2), user = username, password = password, dbname='wrestling', host='localhost')
```

```{r}
dbListTables(conn = my_db_connection)
```

```{r}
dbListTables(conn = my_db_connection)

```

```{r}

dbGetQuery(conn = my_db_connection,
           "SELECT * FROM wrestlers")

```

```{r}
my_db_connection
```

```{r}
keyring_unlock(keyring = "remote")
username <- key_get(service = "remote_username_2", keyring = "remote")
password <- key_get(service = "remote_password_2", keyring = "remote")
keyring_lock(keyring = "remote")

# next, we create a connection to the database
db_connect_remote <- dbConnect(drv = PostgreSQL(max.con = 2), user = username, password = password, dbname='mvhbdgdk', host='34.245.37.126')
```

```{r}
dbGetQuery(db_connect_remote, "SELECT * FROM wrestlers")

```
