---
title: "R Notebook"
output: html_notebook
---
#Part 1
#Q1.1
```{r}
stock_prices <-c(23, 27, 23, 21, 34, 24, 25, 30, 37, 30)
stock_prices
```
#Q1.2
```{r}
day_of_week <-c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
day_of_week
```
#Q2.1
```{r}
day_of_week_factor <- as.factor(day_of_week)
day_of_week_factor
```
#Q2.2 X
```{r}
named_stock_prices <- stock_prices
names(named_stock_prices) <- day_of_week
named_stock_prices
```
#Q3
```{r}
stock_data <- data.frame(stock_prices = stock_prices, day_of_week = day_of_week)
stock_data
```
#Q4
```{r}
stock_list <- list(stock_prices = stock_prices, day_of_week = day_of_week, stock_data = stock_data)
stock_list
```
#Part2.2
#Q1.1
```{r}
stock_prices [4:6]
```
#Q1.2
```{r}
stock_prices [stock_prices > 30]
```
#Q2.1
```{r}
stock_data$day_of_week
```
#Q2.2
Select the rows of the stock_data data frame where the stock_prices are less than 25.
```{r}
stock_prices < 25
```


Q3.1
```{r}
stock_data[,1]
```
#Q3.2
```{r}
stock_data[3,]
```
#Q3.3
```{r}
stock_data[3,1]
```
#Q4
```{r}
stock_list$stock_data
```

#Part 3
```{r}
install.packages("tidyquant")
```


google_prices[ , c("date", "close")]

subset(google_prices, close > mean>(close))
