---
title: "R Notebook"
output: html_notebook
---
```{r}
library(prob)
library(tidyverse)
library(dplyr)
library(janitor)
```

```{r}
phones <- read_csv("data/20190928-items.csv") %>%
  clean_names()
```

```{r}
phones %>%
  group_by(brand) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  top_n(1)
```


```{r}
phones %>%
  group_by(brand) %>%
  count() %>%
  arrange(desc(n)) %>%
  head(1)
  
```

```{r}
phones %>%
  filter(brand == "Samsung") %>%
  ggplot(aes(x = rating)) +
  geom_bar()
```



```{r}
samsung_ratings <- phones %>%
  filter(brand == "Samsung") %>%
  select(rating)

samsung_stats <- phones %>%
  filter(brand == "Samsung") %>%
  summarise(
    count = n(),
    mean = mean(rating),
    sd = sd(rating)
  )
samsung_stats
```

```{r}
samsung_ratings %>%
  ggplot(aes(x = rating)) +
  geom_histogram(aes(y = ..density..), col = "white") +
  stat_function(
    fun = dnorm, 
    args = list(
      mean = samsung_stats$mean,
      sd = samsung_stats$sd
    ),
    col = "red"
  )
```


```{r}
samsung_ratings %>%
  filter(rating >= samsung_stats$mean - samsung_stats$sd) %>%
  filter(rating <= samsung_stats$mean + samsung_stats$sd) %>%
  summarise(prop_within_1sd = n() / nrow(samsung_ratings))

```

```{r}
samsung_ratings %>%
  filter(rating >= samsung_stats$mean -  2 *samsung_stats$sd) %>%
  filter(rating <= samsung_stats$mean + 2 *samsung_stats$sd) %>%
  summarise(prop_within_1sd = n() / nrow(samsung_ratings))

```

```{r}
samsung_ratings %>%
  filter(rating >= samsung_stats$mean - 3 * samsung_stats$sd) %>%
  filter(rating <= samsung_stats$mean + 3 * samsung_stats$sd) %>%
  summarise(prop_within_1sd = n() / nrow(samsung_ratings))

```

